import { Attribute } from './Attribute';
export interface RibbitItem {
  id: number;
  name: string;
  description: string;
  category: string;
  collabId: number;
  twitter: string;
  discord: string;
  website: string;
  endDate: number;
  image: string;
  imageTransparent: string;
  previewImage: string;
  price: number;
  percent: number;
  minted: number;
  supply: number;
  rarity: string;
  walletLimit: number;
  isBoost: boolean;
  isOnSale: boolean;
  isCommunity: boolean;
  isAllowlist: boolean;
  isPhysical: boolean;
  isTrait: boolean;
  amount: number;
  traitLayer: string;
  friendOrigin: string;
}